import { readFile, writeFile, chmod } from 'node:fs/promises'
import { join } from 'node:path'
import { getHooksDir, ensureDir, expandHome } from '../utils/paths.js'
import { getAllProfileDenyRules, profiles } from '../profiles/index.js'
import { SAFE_BASH_ALLOW_RULES, READ_ONLY_BASH_SAFE, READ_ONLY_BASH_FILE_READERS, HARD_TO_REVERSE_ASK_RULES, STRICT_ONLY_ASK_RULES } from '../constants.js'
import type { ClaudeSettings } from '../types.js'

const CSG_RULES_PATH = '~/.claude/csg-rules.json'

export interface CsgManagedRules {
  readonly deny: readonly string[]
  readonly allow: readonly string[]
  readonly ask: readonly string[]
}

/**
 * Get the expanded path to the csg-rules.json file.
 */
export function getCsgRulesPath(): string {
  return expandHome(CSG_RULES_PATH)
}

/**
 * Collect all rules that are managed by csg profiles.
 */
/**
 * Collect all allow rules from all profiles (bare tool names like Read, Bash, etc.)
 */
function collectAllProfileAllowRules(): readonly string[] {
  const allAllow = new Set<string>()
  for (const profile of Object.values(profiles)) {
    for (const rule of profile.allow) {
      allAllow.add(rule)
    }
  }
  return [...allAllow]
}

/**
 * Collect all ask rules from all profiles.
 */
function collectAllProfileAskRules(): readonly string[] {
  const allAsk = new Set<string>()
  for (const profile of Object.values(profiles)) {
    for (const rule of profile.ask ?? []) {
      allAsk.add(rule)
    }
  }
  return [...allAsk]
}

export function collectManagedRuleSets(): {
  readonly managedDeny: ReadonlySet<string>
  readonly managedAllow: ReadonlySet<string>
  readonly managedAsk: ReadonlySet<string>
} {
  return {
    managedDeny: getAllProfileDenyRules(),
    managedAllow: new Set([
      ...SAFE_BASH_ALLOW_RULES,
      ...READ_ONLY_BASH_SAFE,
      ...READ_ONLY_BASH_FILE_READERS,
      ...collectAllProfileAllowRules(),
    ]),
    managedAsk: new Set([
      ...HARD_TO_REVERSE_ASK_RULES,
      ...STRICT_ONLY_ASK_RULES,
      ...collectAllProfileAskRules(),
    ]),
  }
}

/**
 * Extract csg-managed rules from the current settings.
 */
export function extractManagedRules(settings: ClaudeSettings): CsgManagedRules {
  const { managedDeny, managedAllow, managedAsk } = collectManagedRuleSets()
  const deny = (settings.permissions?.deny ?? []).filter(r => managedDeny.has(r))
  const allow = (settings.permissions?.allow ?? []).filter(r => managedAllow.has(r))
  const ask = (settings.permissions?.ask ?? []).filter(r => managedAsk.has(r))
  return { deny, allow, ask }
}

/**
 * Save csg-managed rules to csg-rules.json for later restoration.
 */
export async function saveManagedRules(rules: CsgManagedRules): Promise<string> {
  const rulesPath = getCsgRulesPath()
  await writeFile(rulesPath, JSON.stringify(rules, null, 2) + '\n', 'utf-8')
  return rulesPath
}

/**
 * Load saved csg-managed rules from csg-rules.json.
 */
export async function loadManagedRules(): Promise<CsgManagedRules | null> {
  try {
    const content = await readFile(getCsgRulesPath(), 'utf-8')
    const parsed = JSON.parse(content)
    return {
      deny: Array.isArray(parsed.deny) ? parsed.deny : [],
      allow: Array.isArray(parsed.allow) ? parsed.allow : [],
      ask: Array.isArray(parsed.ask) ? parsed.ask : [],
    }
  } catch {
    return null
  }
}

/**
 * Generate the SessionStart hook script that switches csg rules
 * based on the current permission_mode.
 */
export function generateSessionSwitchScript(): string {
  const rulesPath = getCsgRulesPath()
  const settingsPath = expandHome('~/.claude/settings.json')

  return `#!/bin/bash
# Auto-generated by claude-settings-guard
# SessionStart: crash recovery for csg auto
# If csg-rules.json exists and CSG_PERMISSION_MODE is NOT set,
# it means a previous csg auto session crashed without restoring rules.

# Inside csg auto session — cleanup is handled by csg auto itself
if [ -n "$CSG_PERMISSION_MODE" ]; then
  exit 0
fi

if ! command -v jq &>/dev/null; then
  exit 0
fi

RULES_FILE="${rulesPath}"
SETTINGS_FILE="${settingsPath}"

# No orphaned rules file = nothing to recover
if [ ! -f "$RULES_FILE" ] || [ ! -f "$SETTINGS_FILE" ]; then
  exit 0
fi

CSG_DENY=$(jq -c '.deny // []' "$RULES_FILE" 2>/dev/null)
CSG_ALLOW=$(jq -c '.allow // []' "$RULES_FILE" 2>/dev/null)
CSG_ASK=$(jq -c '.ask // []' "$RULES_FILE" 2>/dev/null)

# Restore csg rules to settings.json (merge, deduplicate)
UPDATED=$(jq --argjson csg_deny "$CSG_DENY" --argjson csg_allow "$CSG_ALLOW" --argjson csg_ask "$CSG_ASK" '
  .permissions.deny = (([.permissions.deny // [] | .[]] + [$csg_deny | .[]] ) | unique) |
  .permissions.allow = (([.permissions.allow // [] | .[]] + [$csg_allow | .[]] ) | unique) |
  .permissions.ask = (([.permissions.ask // [] | .[]] + [$csg_ask | .[]] ) | unique)
' "$SETTINGS_FILE" 2>/dev/null)

if [ -n "$UPDATED" ]; then
  printf '%s\\n' "$UPDATED" > "$SETTINGS_FILE"
  rm -f "$RULES_FILE"
  echo "[csg] クラッシュリカバリ: csg ルールを復元しました" >&2
fi

exit 0
`
}

/**
 * Deploy the session switch hook.
 */
export async function deploySessionSwitchHook(): Promise<string> {
  const hooksDir = getHooksDir()
  await ensureDir(hooksDir)
  const hookPath = join(hooksDir, 'csg-session.sh')
  const script = generateSessionSwitchScript()
  await writeFile(hookPath, script, 'utf-8')
  await chmod(hookPath, 0o755)
  return hookPath
}

/**
 * Register the session switch hook in settings.json.
 */
export function mergeSessionSwitchHookIntoSettings(
  settings: ClaudeSettings,
  hookPath: string,
): ClaudeSettings {
  const hooks = settings.hooks ?? {}
  const existing = hooks.SessionStart ?? []

  // Also check legacy top-level SessionStart
  const legacyExists = (settings.SessionStart ?? []).some(rule =>
    rule.hooks.some(h => h.command.includes('csg-session'))
  )

  const alreadyExists = existing.some(rule =>
    rule.hooks.some(h => h.command.includes('csg-session'))
  )

  if (alreadyExists) {
    // Remove legacy top-level entry if it exists
    if (legacyExists) {
      const cleanedLegacy = (settings.SessionStart ?? []).filter(rule =>
        !rule.hooks.some(h => h.command.includes('csg-session'))
      )
      return {
        ...settings,
        SessionStart: cleanedLegacy.length > 0 ? cleanedLegacy : undefined,
      }
    }
    return settings
  }

  const newRule = {
    matcher: '*',
    hooks: [{
      type: 'command' as const,
      command: hookPath,
    }],
  }

  // Remove legacy top-level entry if it exists
  const cleanedSettings = legacyExists
    ? (() => {
        const cleanedLegacy = (settings.SessionStart ?? []).filter(rule =>
          !rule.hooks.some(h => h.command.includes('csg-session'))
        )
        return {
          ...settings,
          SessionStart: cleanedLegacy.length > 0 ? cleanedLegacy : undefined,
        }
      })()
    : settings

  return {
    ...cleanedSettings,
    hooks: {
      ...hooks,
      SessionStart: [...existing, newRule],
    },
  }
}
