import { LEGACY_COLON_PATTERN, MODERN_SPACE_PATTERN } from '../constants.js'
import type { ClaudeSettings } from '../types.js'

interface DenyRule {
  readonly toolName: string
  readonly pattern: string
  readonly regex: string
}

function assertSafePattern(pattern: string): void {
  if (/[`$;|&\n\r]/.test(pattern)) {
    throw new Error(`Deny pattern contains unsafe shell characters: ${pattern}`)
  }
}

function patternToRegex(pattern: string): string {
  assertSafePattern(pattern)
  return pattern
    .replace(/\./g, '\\.')
    .replace(/\*\*/g, '<<GLOBSTAR>>')
    .replace(/\*/g, '.*')
    .replace(/<<GLOBSTAR>>/g, '.*')
    .replace(/\?/g, '.')
}

function parseDenyPattern(pattern: string): DenyRule | null {
  // Legacy colon syntax
  const legacyMatch = pattern.match(LEGACY_COLON_PATTERN)
  if (legacyMatch) {
    const [, toolName, arg] = legacyMatch
    return {
      toolName,
      pattern,
      regex: patternToRegex(`${arg} *`),
    }
  }

  // Modern space syntax
  const modernMatch = pattern.match(MODERN_SPACE_PATTERN)
  if (modernMatch) {
    const [, toolName, arg] = modernMatch
    return {
      toolName,
      pattern,
      regex: patternToRegex(arg),
    }
  }

  return null
}

export function generateEnforceScript(denyRules: readonly string[]): string {
  const parsedRules = denyRules
    .map(parseDenyPattern)
    .filter((r): r is DenyRule => r !== null)

  // Group by tool name
  const byTool = new Map<string, DenyRule[]>()
  for (const rule of parsedRules) {
    const existing = byTool.get(rule.toolName) ?? []
    byTool.set(rule.toolName, [...existing, rule])
  }

  const toolChecks: string[] = []

  for (const [toolName, rules] of byTool) {
    const conditions = rules.map(r => {
      if (toolName === 'Bash') {
        return `    [[ "$command" =~ ^${r.regex} ]]`
      } else if (toolName === 'Read' || toolName === 'Write' || toolName === 'Edit') {
        return `    [[ "$file_path" =~ ${r.regex} ]]`
      }
      return `    [[ "$tool_input" =~ ${r.regex} ]]`
    })

    const inputExtraction = toolName === 'Bash'
      ? '  command=$(printf \'%s\' "$input" | jq -r \'.tool_input.command // ""\')'
      : toolName === 'Read' || toolName === 'Write' || toolName === 'Edit'
        ? '  file_path=$(printf \'%s\' "$input" | jq -r \'.tool_input.file_path // ""\')'
        : '  tool_input=$(printf \'%s\' "$input")'

    toolChecks.push(`if [ "$TOOL_NAME" = "${toolName}" ]; then
${inputExtraction}
  if
${conditions.join(' ||\n')}
  then
    reason="BLOCKED by enforce-permissions: deny rule matched for ${toolName}"
    jq -n --arg reason "$reason" '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: $reason
      }
    }'
    echo "$reason" >&2
    exit 2
  fi
fi`)
  }

  return `#!/bin/bash
# Auto-generated by claude-settings-guard
# Layer 2: PreToolUse enforcement hook
# Reads deny rules and independently blocks matching tool calls
# This is a backup for settings.json deny rules that may not work due to bugs

input=$(cat)

${toolChecks.join('\n\n')}

exit 0
`
}

export function generateHookRegistration(): {
  readonly matcher: string
  readonly hooks: readonly { readonly type: string; readonly command: string }[]
} {
  return {
    matcher: '*',
    hooks: [{
      type: 'command',
      command: '~/.claude/hooks/enforce-permissions.sh',
    }],
  }
}

export function mergeHookIntoSettings(
  settings: ClaudeSettings,
  hookPath: string
): ClaudeSettings {
  const existingPreToolUse = settings.PreToolUse ?? []

  // Check if already registered
  const alreadyExists = existingPreToolUse.some(rule =>
    rule.hooks.some(h => h.command.includes('enforce-permissions'))
  )

  if (alreadyExists) return settings

  const newRule = {
    matcher: '*',
    hooks: [{
      type: 'command' as const,
      command: hookPath,
    }],
  }

  return {
    ...settings,
    PreToolUse: [...existingPreToolUse, newRule],
  }
}
