import type { ClaudeSettings } from '../types.js'
import {
  groupRulesByTool,
  generateBashToolCheck,
  generateNonBashToolCheck,
} from './hook-script-builder.js'

function generateSplitSubcommands(): string {
  const lines = [
    '# Split shell command into subcommands (pipes, chains, substitutions)',
    'split_subcommands() {',
    '  local cmd="$1"',
    '',
    '  # Extract $() contents and output them separately',
    "  local extracted=$(printf '%s' \"$cmd\" | grep -oE '\\$\\([^)]+\\)' | sed 's/^\\$(//' | sed 's/)$//')",
    '',
    '  # Remove $() and <() blocks from main command',
    "  local cleaned=$(printf '%s' \"$cmd\" | sed -E 's/\\$\\([^)]*\\)//g; s/<\\([^)]*\\)//g')",
    '',
    '  # Remove subshell parens and brace groups',
    "  cleaned=$(printf '%s' \"$cleaned\" | sed -E 's/^[[:space:]]*\\(//; s/\\)[[:space:]]*$//; s/^[[:space:]]*\\{//; s/\\}[[:space:]]*$//')",
    '',
    '  # Replace operators with newlines (multi-char first)',
    "  cleaned=$(printf '%s' \"$cleaned\" | sed 's/&&/\\n/g' | sed 's/||/\\n/g' | sed 's/|/\\n/g' | sed 's/;/\\n/g')",
    '',
    '  # Output main parts (trimmed)',
    "  printf '%s\\n' \"$cleaned\" | while IFS= read -r line; do",
    "    line=$(printf '%s' \"$line\" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')",
    '    [ -n "$line" ] && printf \'%s\\n\' "$line"',
    '  done',
    '',
    '  # Output extracted $() parts (recursively split)',
    '  if [ -n "$extracted" ]; then',
    '    printf \'%s\\n\' "$extracted" | while IFS= read -r sub; do',
    '      [ -z "$sub" ] && continue',
    '      split_subcommands "$sub"',
    '    done',
    '  fi',
    '}',
  ]
  return lines.join('\n')
}

export function generateEnforceScript(denyRules: readonly string[]): string {
  const byTool = groupRulesByTool(denyRules)

  const hasBashRules = byTool.has('Bash')
  const toolChecks: string[] = []

  for (const [toolName, rules] of byTool) {
    if (toolName === 'Bash') {
      toolChecks.push(generateBashToolCheck(rules))
    } else {
      toolChecks.push(generateNonBashToolCheck(toolName, rules))
    }
  }

  const splitFn = hasBashRules ? `\n${generateSplitSubcommands()}\n` : ''

  return `#!/bin/bash
# Auto-generated by claude-settings-guard
# Layer 2: PreToolUse enforcement hook
# Reads deny rules and independently blocks matching tool calls
# This is a backup for settings.json deny rules that may not work due to bugs

input=$(cat)
TOOL_NAME=$(printf '%s' "$input" | jq -r '.tool_name // ""')
${splitFn}
${toolChecks.join('\n\n')}

exit 0
`
}

export function generateHookRegistration(): {
  readonly matcher: string
  readonly hooks: readonly { readonly type: string; readonly command: string }[]
} {
  return {
    matcher: '*',
    hooks: [{
      type: 'command',
      command: '~/.claude/hooks/enforce-permissions.sh',
    }],
  }
}

export function mergeHookIntoSettings(
  settings: ClaudeSettings,
  hookPath: string
): ClaudeSettings {
  const existingPreToolUse = settings.PreToolUse ?? []

  // Check if already registered
  const alreadyExists = existingPreToolUse.some(rule =>
    rule.hooks.some(h => h.command.includes('enforce-permissions'))
  )

  if (alreadyExists) return settings

  const newRule = {
    matcher: '*',
    hooks: [{
      type: 'command' as const,
      command: hookPath,
    }],
  }

  return {
    ...settings,
    PreToolUse: [...existingPreToolUse, newRule],
  }
}
