import { writeFile, chmod } from 'node:fs/promises'
import { join } from 'node:path'
import { getHooksDir, ensureDir, expandHome } from '../utils/paths.js'
import type { ClaudeSettings } from '../types.js'

const SESSION_DIAGNOSE_SCRIPT = `#!/bin/bash
# Auto-generated by claude-settings-guard
# SessionStart: auto-diagnose settings on Claude Code startup

result=$(npx claude-settings-guard diagnose --json --quiet 2>/dev/null)
exit_code=$?

if [ $exit_code -ne 0 ] && [ -n "$result" ]; then
  # Extract critical/high issues and output to stderr (visible to Claude)
  echo "[csg] Settings issues detected:" >&2
  echo "$result" >&2
fi

exit 0
`

export function generateSessionDiagnoseScript(): string {
  return SESSION_DIAGNOSE_SCRIPT
}

export async function deploySessionHook(): Promise<string> {
  const hooksDir = getHooksDir()
  await ensureDir(hooksDir)
  const hookPath = join(hooksDir, 'session-diagnose.sh')
  await writeFile(hookPath, SESSION_DIAGNOSE_SCRIPT, 'utf-8')
  await chmod(hookPath, 0o755)
  return hookPath
}

export function mergeSessionHookIntoSettings(
  settings: ClaudeSettings,
  hookPath: string
): ClaudeSettings {
  const existingSessionStart = settings.SessionStart ?? []

  const alreadyExists = existingSessionStart.some(rule =>
    rule.hooks.some(h => h.command.includes('session-diagnose'))
  )

  if (alreadyExists) return settings

  const newRule = {
    matcher: '',
    hooks: [{
      type: 'command' as const,
      command: hookPath,
    }],
  }

  return {
    ...settings,
    SessionStart: [...existingSessionStart, newRule],
  }
}

export async function installSessionHook(settings: ClaudeSettings): Promise<{
  readonly settings: ClaudeSettings
  readonly hookPath: string
}> {
  const hookPath = await deploySessionHook()
  const expandedHookPath = expandHome('~/.claude/hooks/session-diagnose.sh')
  const updatedSettings = mergeSessionHookIntoSettings(settings, expandedHookPath)
  return { settings: updatedSettings, hookPath }
}
